{% set name = "cma" %}
{% set version = "3.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 47ac71ddd2b9a922daa601516064a585a1a3dbbae7802bca935db25e525547eb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True # [py<36]

requirements:
  host:
    - pip
    - python
    - numpy
    - wheel
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - cma
    - cma.utilities

about:
  home: https://github.com/CMA-ES/pycma
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CMA-ES, Covariance Matrix Adaptation Evolution Strategy for non-linear numerical optimization in Python
  doc_url: http://cma.gforge.inria.fr/apidocs-pycma/
  dev_url: https://github.com/CMA-ES/pycma
  description: |
    The Covariance Matrix Adaptation Evolution Strategy (CMA-ES) is a stochastic derivative-free numerical 
    optimization algorithm for difficult (non-convex, ill-conditioned, multi-modal, rugged, noisy) optimization
    problems in continuous search spaces.
extra:
  recipe-maintainers:
    - rpanai
